// 併用禁忌・重大な相互作用データベース
// 出典: 各薬剤添付文書（2026年3月時点）

const INTERACTION_DATA = [
  // ========== 併用禁忌（Level 1）==========
  // アゾール系抗真菌薬
  { drugA: "イトラコナゾール", drugB: "ピモジド", level: 1, reason: "QT延長、心室性不整脈のリスク" },
  { drugA: "イトラコナゾール", drugB: "キニジン", level: 1, reason: "QT延長、心室性不整脈のリスク" },
  { drugA: "イトラコナゾール", drugB: "ドフェチリド", level: 1, reason: "QT延長、心室性不整脈のリスク" },
  { drugA: "イトラコナゾール", drugB: "エプレレノン", level: 1, reason: "高カリウム血症のリスク" },
  { drugA: "イトラコナゾール", drugB: "シロリムス", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "イトラコナゾール", drugB: "シベンゾリン", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "イトラコナゾール", drugB: "トルバプタン", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "イトラコナゾール", drugB: "フィネレノン", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "イトラコナゾール", drugB: "ブロナンセリン", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "イトラコナゾール", drugB: "アゼルニジピン", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "イトラコナゾール", drugB: "ロミタピド", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "イトラコナゾール", drugB: "リバーロキサバン", level: 1, reason: "出血リスク増大" },
  { drugA: "イトラコナゾール", drugB: "スボレキサント", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "イトラコナゾール", drugB: "イブルチニブ", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "イトラコナゾール", drugB: "ラスミジカム", level: 1, reason: "血中濃度上昇による有害事象" },
  
  { drugA: "フルコナゾール", drugB: "エプレレノン", level: 1, reason: "高カリウム血症のリスク" },
  { drugA: "フルコナゾール", drugB: "フィネレノン", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "フルコナゾール", drugB: "トルバプタン", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "フルコナゾール", drugB: "スボレキサント", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "フルコナゾール", drugB: "トボガスチャット", level: 1, reason: "血中濃度上昇による有害事象" },
  
  { drugA: "ボリコナゾール", drugB: "エフェドリン", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "ボリコナゾール", drugB: "トリアゾラム", level: 1, reason: "作用増強・作用時間延長" },
  { drugA: "ボリコナゾール", drugB: "ピモジド", level: 1, reason: "QT延長、心室性不整脈のリスク" },
  { drugA: "ボリコナゾール", drugB: "キニジン", level: 1, reason: "QT延長、心室性不整脈のリスク" },
  { drugA: "ボリコナゾール", drugB: "ドフェチリド", level: 1, reason: "QT延長、心室性不整脈のリスク" },
  { drugA: "ボリコナゾール", drugB: "シロリムス", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "ボリコナゾール", drugB: "リファブチン", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "ボリコナゾール", drugB: "リバーロキサバン", level: 1, reason: "出血リスク増大" },
  { drugA: "ボリコナゾール", drugB: "スボレキサント", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "ボリコナゾール", drugB: "イブルチニブ", level: 1, reason: "血中濃度上昇による有害事象" },
  
  { drugA: "ポサコナゾール", drugB: "エプレレノン", level: 1, reason: "高カリウム血症のリスク" },
  { drugA: "ポサコナゾール", drugB: "フィネレノン", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "ポサコナゾール", drugB: "シロリムス", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "ポサコナゾール", drugB: "ピモジド", level: 1, reason: "QT延長、心室性不整脈のリスク" },
  { drugA: "ポサコナゾール", drugB: "キニジン", level: 1, reason: "QT延長、心室性不整脈のリスク" },
  { drugA: "ポサコナゾール", drugB: "ドフェチリド", level: 1, reason: "QT延長、心室性不整脈のリスク" },
  
  // マクロライド系
  { drugA: "クラリスロマイシン", drugB: "ピモジド", level: 1, reason: "QT延長、心室性不整脈のリスク" },
  { drugA: "クラリスロマイシン", drugB: "キニジン", level: 1, reason: "QT延長、心室性不整脈のリスク" },
  { drugA: "クラリスロマイシン", drugB: "ドフェチリド", level: 1, reason: "QT延長、心室性不整脈のリスク" },
  { drugA: "クラリスロマイシン", drugB: "シロリムス", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "クラリスロマイシン", drugB: "トルバプタン", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "クラリスロマイシン", drugB: "エルゴタミン", level: 1, reason: "四肢虚血等のリスク" },
  { drugA: "クラリスロマイシン", drugB: "ジヒドロエルゴタミン", level: 1, reason: "四肢虚血等のリスク" },
  { drugA: "クラリスロマイシン", drugB: "エルゴメトリン", level: 1, reason: "四肢虚血等のリスク" },
  { drugA: "クラリスロマイシン", drugB: "メチルエルゴメトリン", level: 1, reason: "四肢虚血等のリスク" },
  { drugA: "クラリスロマイシン", drugB: "ロミタピド", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "クラリスロマイシン", drugB: "リバーロキサバン", level: 1, reason: "出血リスク増大" },
  { drugA: "クラリスロマイシン", drugB: "スボレキサント", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "クラリスロマイシン", drugB: "ラスミジカム", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "クラリスロマイシン", drugB: "トリアゾラム", level: 1, reason: "作用増強・作用時間延長" },
  
  { drugA: "エリスロマイシン", drugB: "ピモジド", level: 1, reason: "QT延長、心室性不整脈のリスク" },
  { drugA: "エリスロマイシン", drugB: "シサプリド", level: 1, reason: "QT延長、心室性不整脈のリスク" },
  { drugA: "エリスロマイシン", drugB: "テレノレノン", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "エリスロマイシン", drugB: "トリアゾラム", level: 1, reason: "作用増強・作用時間延長" },
  
  // CYP3A4阻害薬（その他）
  { drugA: "リトナビル", drugB: "アムロジピン", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "リトナビル", drugB: "バルデナフィル", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "リトナビル", drugB: "シルデナフィル", level: 1, reason: "血中濃度上昇による有害事象（肺高血圧症以外）" },
  { drugA: "リトナビル", drugB: "タダラフィル", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "リトナビル", drugB: "トリアゾラム", level: 1, reason: "作用増強・作用時間延長" },
  { drugA: "リトナビル", drugB: "ミダゾラム", level: 1, reason: "作用増強・作用時間延長" },
  { drugA: "リトナビル", drugB: "シンバスタチン", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "リトナビル", drugB: "ロバスタチン", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "リトナビル", drugB: "ロミタピド", level: 1, reason: "血中濃度上昇による有害事象" },
  
  { drugA: "コビシスタット", drugB: "アムロジピン", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "コビシスタット", drugB: "バルデナフィル", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "コビシスタット", drugB: "シルデナフィル", level: 1, reason: "血中濃度上昇による有害事象（肺高血圧症以外）" },
  { drugA: "コビシスタット", drugB: "タダラフィル", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "コビシスタット", drugB: "トリアゾラム", level: 1, reason: "作用増強・作用時間延長" },
  { drugA: "コビシスタット", drugB: "ミダゾラム", level: 1, reason: "作用増強・作用時間延長" },
  { drugA: "コビシスタット", drugB: "シンバスタチン", level: 1, reason: "血中濃度上昇による有害事象" },
  { drugA: "コビシスタット", drugB: "ロバスタチン", level: 1, reason: "血中濃度上昇による有害事象" },
  
  // ========== 重大な副作用（Level 2）==========
  { drugA: "ワルファリン", drugB: "ミコナゾール", level: 2, reason: "出血リスク増大" },
  { drugA: "ワルファリン", drugB: "スルファメトキサゾール・トリメトプリム", level: 2, reason: "出血リスク増大" },
  { drugA: "ワルファリン", drugB: "メトロニダゾール", level: 2, reason: "出血リスク増大" },
  { drugA: "ワルファリン", drugB: "フルタミド", level: 2, reason: "出血リスク増大" },
  { drugA: "ワルファリン", drugB: "フルコナゾール", level: 2, reason: "出血リスク増大" },
  { drugA: "ワルファリン", drugB: "シメチジン", level: 2, reason: "出血リスク増大" },
  { drugA: "ワルファリン", drugB: "オメプラゾール", level: 2, reason: "出血リスク増大" },
  { drugA: "ワルファリン", drugB: "アミオダロン", level: 2, reason: "出血リスク増大" },
  { drugA: "ワルファリン", drugB: "シクロホスファミド", level: 2, reason: "出血リスク増大" },
  { drugA: "ワルファリン", drugB: "エトトレキセート", level: 2, reason: "出血リスク増大" },
  
  { drugA: "メトトレキサート", drugB: "ST合剤", level: 2, reason: "骨髄抑制・汎血球減少" },
  { drugA: "メトトレキサート", drugB: "スルファメトキサゾール", level: 2, reason: "骨髄抑制・汎血球減少" },
  { drugA: "メトトレキサート", drugB: "トリメトプリム", level: 2, reason: "骨髄抑制・汎血球減少" },
  { drugA: "メトトレキサート", drugB: "フェニルブタゾン", level: 2, reason: "骨髄抑制・汎血球減少" },
  { drugA: "メトトレキサート", drugB: "フェニトイン", level: 2, reason: "骨髄抑制・汎血球減少" },
  { drugA: "メトトレキサート", drugB: "テトラサイクリン", level: 2, reason: "肝毒性リスク" },
  { drugA: "メトトレキサート", drugB: "クロラムフェニコール", level: 2, reason: "骨髄抑制・汎血球減少" },
  
  { drugA: "MA阻害薬", drugB: "三環系抗うつ薬", level: 2, reason: "発作、高熱、昏睡等のリスク" },
  { drugA: "MA阻害薬", drugB: "SSRI", level: 2, reason: "セロトニン症候群のリスク" },
  { drugA: "MA阻害薬", drugB: "SNRI", level: 2, reason: "セロトニン症候群のリスク" },
  { drugA: "MA阻害薬", drugB: "トラマドール", level: 2, reason: "セロトニン症候群のリスク" },
  { drugA: "MA阻害薬", drugB: "ペチジン", level: 2, reason: "興奮、発汗、昏睡等のリスク" },
  
  { drugA: "SSRI", drugB: "MA阻害薬", level: 2, reason: "セロトニン症候群のリスク" },
  { drugA: "SSRI", drugB: "トラマドール", level: 2, reason: "セロトニン症候群のリスク" },
  { drugA: "SSRI", drugB: "トリプタン系", level: 2, reason: "セロトニン症候群のリスク" },
  { drugA: "SSRI", drugB: "リネゾリド", level: 2, reason: "セロトニン症候群のリスク" },
  { drugA: "SSRI", drugB: "メチレンブルー", level: 2, reason: "セロトニン症候群のリスク" },
  
  { drugA: "フロセミド", drugB: "アミノグリコシド系抗生物質", level: 2, reason: "第8脳神経障害・腎障害リスク増大" },
  { drugA: "フロセミド", drugB: "ゲンタマイシン", level: 2, reason: "第8脳神経障害・腎障害リスク増大" },
  { drugA: "フロセミド", drugB: "トブラマイシン", level: 2, reason: "第8脳神経障害・腎障害リスク増大" },
  { drugA: "フロセミド", drugB: "アミカシン", level: 2, reason: "第8脳神経障害・腎障害リスク増大" },
  
  { drugA: "ACE阻害薬", drugB: "カリウム保持性利尿薬", level: 2, reason: "高カリウム血症のリスク" },
  { drugA: "ACE阻害薬", drugB: "スピロノラクトン", level: 2, reason: "高カリウム血症のリスク" },
  { drugA: "ACE阻害薬", drugB: "エプレレノン", level: 2, reason: "高カリウム血症のリスク" },
  { drugA: "ARB", drugB: "カリウム保持性利尿薬", level: 2, reason: "高カリウム血症のリスク" },
  { drugA: "ARB", drugB: "スピロノラクトン", level: 2, reason: "高カリウム血症のリスク" },
  { drugA: "ARB", drugB: "エプレレノン", level: 2, reason: "高カリウム血症のリスク" },
  
  { drugA: "NSAIDs", drugB: "リチウム", level: 2, reason: "リチウム中毒のリスク" },
  { drugA: "インドメタシン", drugB: "リチウム", level: 2, reason: "リチウム中毒のリスク" },
  { drugA: "ジクロフェナク", drugB: "リチウム", level: 2, reason: "リチウム中毒のリスク" },
  { drugA: "イブプロフェン", drugB: "リチウム", level: 2, reason: "リチウム中毒のリスク" },
  
  { drugA: "シクロスポリン", drugB: "NSAIDs", level: 2, reason: "腎障害リスク増大" },
  { drugA: "シクロスポリン", drugB: "アミノグリコシド系", level: 2, reason: "腎障害リスク増大" },
  { drugA: "シクロスポリン", drugB: "アムホテリシンB", level: 2, reason: "腎障害リスク増大" },
  { drugA: "シクロスポリン", drugB: "トリメトプリム", level: 2, reason: "腎障害リスク増大" },
  
  { drugA: "デジゴキシン", drugB: "アミオダロン", level: 2, reason: "ジギタリス中毒のリスク" },
  { drugA: "デジゴキシン", drugB: "キニジン", level: 2, reason: "ジギタリス中毒のリスク" },
  { drugA: "デジゴキシン", drugB: "ベラパミル", level: 2, reason: "ジギタリス中毒のリスク" },
  { drugA: "デジゴキシン", drugB: "クラリスロマイシン", level: 2, reason: "ジギタリス中毒のリスク" },
  { drugA: "デジゴキシン", drugB: "イトラコナゾール", level: 2, reason: "ジギタリス中毒のリスク" },
  
  { drugA: "テオフィリン", drugB: "シプロフロキサシン", level: 2, reason: "テオフィリン中毒のリスク" },
  { drugA: "テオフィリン", drugB: "エノキサシン", level: 2, reason: "テオフィリン中毒のリスク" },
  { drugA: "テオフィリン", drugB: "シメチジン", level: 2, reason: "テオフィリン中毒のリスク" },
  { drugA: "テオフィリン", drugB: "インターフェロン", level: 2, reason: "テオフィリン中毒のリスク" },
  
  // ========== 併用注意（Level 3）==========
  { drugA: "降圧薬", drugB: "NSAIDs", level: 3, reason: "降圧効果減弱" },
  { drugA: "降圧薬", drugB: "ステロイド", level: 3, reason: "降圧効果減弱・浮腫" },
  { drugA: "利尿薬", drugB: "NSAIDs", level: 3, reason: "利尿効果減弱・腎障害リスク" },
  { drugA: "抗凝固薬", drugB: "NSAIDs", level: 3, reason: "出血リスク増大" },
  { drugA: "抗凝固薬", drugB: "抗血小板薬", level: 3, reason: "出血リスク増大" },
  { drugA: "DOAC", drugB: "抗血小板薬", level: 3, reason: "出血リスク増大" },
  { drugA: "DOAC", drugB: "NSAIDs", level: 3, reason: "出血リスク増大" },
  { drugA: "ベンゾジアゼピン系", drugB: "中枢神経抑制薬", level: 3, reason: "作用増強" },
  { drugA: "ベンゾジアゼピン系", drugB: "アルコール", level: 3, reason: "作用増強" },
  { drugA: "オピオイド", drugB: "ベンゾジアゼピン系", level: 3, reason: "呼吸抑制・鎮静リスク" },
  { drugA: "オピオイド", drugB: "中枢神経抑制薬", level: 3, reason: "呼吸抑制・鎮静リスク" },
  { drugA: "血糖降下薬", drugB: "β遮断薬", level: 3, reason: "低血糖症状マスク" },
  { drugA: "血糖降下薬", drugB: "フルオキノロン系", level: 3, reason: "低血糖・高血糖リスク" },
  { drugA: "メトホルミン", drugB: "ヨード造影剤", level: 3, reason: "乳酸アシドーシスのリスク" },
  { drugA: "ビグアナイド系", drugB: "ヨード造影剤", level: 3, reason: "乳酸アシドーシスのリスク" },
  { drugA: "スルホニル尿素系", drugB: "フルコナゾール", level: 3, reason: "低血糖リスク増大" },
  { drugA: "経口血糖降下薬", drugB: "クラリスロマイシン", level: 3, reason: "低血糖リスク増大" },
  { drugA: "ステロイド", drugB: "抗凝固薬", level: 3, reason: "出血リスク増大" },
  { drugA: "ステロイド", drugB: "血糖降下薬", level: 3, reason: "血糖上昇" },
  { drugA: "ステロイド", drugB: "利尿薬", level: 3, reason: "低カリウム血症リスク" },
  { drugA: "ステロイド", drugB: "NSAIDs", level: 3, reason: "消化性潰瘍リスク増大" },
  { drugA: "テトラサイクリン系", drugB: "制酸剤", level: 3, reason: "吸収低下" },
  { drugA: "ニューキノロン系", drugB: "制酸剤", level: 3, reason: "吸収低下" },
  { drugA: "ニューキノロン系", drugB: "多価陽イオン", level: 3, reason: "吸収低下" },
  { drugA: "ニューキノロン系", drugB: "鉄剤", level: 3, reason: "吸収低下" },
  { drugA: "ニューキノロン系", drugB: "カルシウム", level: 3, reason: "吸収低下" },
  { drugA: "ニューキノロン系", drugB: "マグネシウム", level: 3, reason: "吸収低下" },
  { drugA: "ビスホスホネート", drugB: "制酸剤", level: 3, reason: "吸収低下" },
  { drugA: "ビスホスホネート", drugB: "カルシウム", level: 3, reason: "吸収低下" },
  { drugA: "甲状腺ホルモン", drugB: "制酸剤", level: 3, reason: "吸収低下" },
  { drugA: "甲状腺ホルモン", drugB: "鉄剤", level: 3, reason: "吸収低下" },
  { drugA: "甲状腺ホルモン", drugB: "カルシウム", level: 3, reason: "吸収低下" },
  { drugA: "甲状腺ホルモン", drugB: "コレスチラミン", level: 3, reason: "吸収低下" },
  
  // ========== 抗てんかん薬の相互作用 ==========
  // バルプロ酸ナトリウム
  { drugA: "バルプロ酸", drugB: "カルバマゼピン", level: 2, reason: "カルバマゼピン中毒のリスク" },
  { drugA: "バルプロ酸", drugB: "ラモトリギン", level: 2, reason: "ラモトリギン血中濃度上昇・皮疹リスク" },
  { drugA: "バルプロ酸", drugB: "フェノバルビタール", level: 2, reason: "フェノバルビタール血中濃度上昇" },
  { drugA: "バルプロ酸", drugB: "メルカプトプリン", level: 2, reason: "肝毒性リスク増大" },
  { drugA: "バルプロ酸", drugB: "カルバペネム系", level: 2, reason: "バルプロ酸血中濃度急激低下・発作リスク" },
  { drugA: "バルプロ酸", drugB: "ドルテプラーズ", level: 2, reason: "バルプロ酸血中濃度急激低下・発作リスク" },
  { drugA: "バルプロ酸", drugB: "パネバクタム", level: 2, reason: "バルプロ酸血中濃度急激低下・発作リスク" },
  { drugA: "バルプロ酸", drugB: "ビオプラゾン", level: 2, reason: "バルプロ酸血中濃度急激低下・発作リスク" },
  
  // カルバマゼピン
  { drugA: "カルバマゼピン", drugB: "エリスロマイシン", level: 2, reason: "カルバマゼピン中毒のリスク" },
  { drugA: "カルバマゼピン", drugB: "クラリスロマイシン", level: 2, reason: "カルバマゼピン中毒のリスク" },
  { drugA: "カルバマゼピン", drugB: "フルコナゾール", level: 2, reason: "カルバマゼピン中毒のリスク" },
  { drugA: "カルバマゼピン", drugB: "イトラコナゾール", level: 2, reason: "カルバマゼピン中毒のリスク" },
  { drugA: "カルバマゼピン", drugB: "ボリコナゾール", level: 2, reason: "カルバマゼピン中毒のリスク" },
  { drugA: "カルバマゼピン", drugB: "ダナゾール", level: 2, reason: "カルバマゼピン中毒のリスク" },
  { drugA: "カルバマゼピン", drugB: "ベラパミル", level: 2, reason: "カルバマゼピン中毒のリスク" },
  { drugA: "カルバマゼピン", drugB: "ジルチアゼム", level: 2, reason: "カルバマゼピン中毒のリスク" },
  { drugA: "カルバマゼピン", drugB: "シメチジン", level: 3, reason: "カルバマゼピン血中濃度上昇" },
  
  // フェニトイン
  { drugA: "フェニトイン", drugB: "フルコナゾール", level: 2, reason: "フェニトイン中毒のリスク" },
  { drugA: "フェニトイン", drugB: "イトラコナゾール", level: 2, reason: "フェニトイン中毒のリスク" },
  { drugA: "フェニトイン", drugB: "ボリコナゾール", level: 2, reason: "フェニトイン中毒のリスク" },
  { drugA: "フェニトイン", drugB: "シメチジン", level: 3, reason: "フェニトイン血中濃度上昇" },
  { drugA: "フェニトイン", drugB: "アモキサピン", level: 2, reason: "フェニトイン血中濃度上昇" },
  { drugA: "フェニトイン", drugB: "クロラムフェニコール", level: 2, reason: "フェニトイン中毒のリスク" },
  { drugA: "フェニトイン", drugB: "イソニアジド", level: 2, reason: "フェニトイン中毒のリスク" },
  { drugA: "フェニトイン", drugB: "スルファメトキサゾール", level: 2, reason: "フェニトイン中毒のリスク" },
  
  // ラモトリギン
  { drugA: "ラモトリギン", drugB: "バルプロ酸", level: 2, reason: "ラモトリギン血中濃度上昇・皮疹リスク" },
  { drugA: "ラモトリギン", drugB: "カルバマゼピン", level: 3, reason: "ラモトリギン血中濃度低下" },
  { drugA: "ラモトリギン", drugB: "フェニトイン", level: 3, reason: "ラモトリギン血中濃度低下" },
  { drugA: "ラモトリギン", drugB: "フェノバルビタール", level: 3, reason: "ラモトリギン血中濃度低下" },
  { drugA: "ラモトリギン", drugB: "プリミドン", level: 3, reason: "ラモトリギン血中濃度低下" },
  
  // トピラマート
  { drugA: "トピラマート", drugB: "カルバマゼピン", level: 3, reason: "トピラマート血中濃度低下" },
  { drugA: "トピラマート", drugB: "フェニトイン", level: 3, reason: "トピラマート血中濃度低下" },
  { drugA: "トピラマート", drugB: "バルプロ酸", level: 3, reason: "アンモニア血症リスク" },
  
  // フェノバルビタール
  { drugA: "フェノバルビタール", drugB: "バルプロ酸", level: 2, reason: "フェノバルビタール血中濃度上昇" },
  { drugA: "フェノバルビタール", drugB: " DOAC", level: 3, reason: "DOAC血中濃度低下・効果減弱" },
  { drugA: "フェノバルビタール", drugB: "ワルファリン", level: 2, reason: "ワルファリン効果減弱" },
  { drugA: "フェノバルビタール", drugB: "ステロイド", level: 3, reason: "ステロイド効果減弱" },
  { drugA: "フェノバルビタール", drugB: "テオフィリン", level: 3, reason: "テオフィリン血中濃度低下" },
  { drugA: "フェノバルビタール", drugB: "経口避妊薬", level: 3, reason: "避妊効果減弱" },
];

// 互換性確保（グローバル公開）
if (typeof window !== 'undefined') {
  window.INTERACTION_DATA = INTERACTION_DATA;
}
